Version 0.1.9

diff --git a/tools/aqdtinstall.in b/tools/aqdtinstall.in
--- a/tools/aqdtinstall.in
+++ b/tools/aqdtinstall.in
@@ -10,7 +10,7 @@ DEFAULT_GROUP="aquila"
 DEFAULT_SHELL="/bin/false"
 DEFAULT_HOME="/home/${DEFAULT_USER}"
 
-CONFIGFILES="accounts.conf chatroom.conf clientbanlist.conf hardban.conf hub.conf nickban.conf softban.conf trigger.conf"
+CONFIGFILES="accounts.conf chatroom.conf clientbanlist.conf hardban.conf hub.conf softban.conf restrict.conf lua.conf trigger.conf lua.conf aquila.pid"
 
 unset USER
 unset GROUP
@@ -20,6 +20,20 @@ unset ECHO
 unset dohelp
 unset force
 unset verbose
+
+if [ -z "${distro}" ];
+then
+        if [ -f /etc/lsb-release ]
+        then
+                distro=`cat /etc/lsb-release | head -n 1 | cut -d '=' -f 2`
+        else if [ -f /etc/debian_version ]
+        then
+                distro=Debian
+        else
+                distro=`cat /etc/*-release | head -n 1 | cut -d' ' -f 1`
+        fi
+        fi
+fi
 
 while [ -n "$1" ];
 do
@@ -126,101 +140,152 @@ then
 fi;
 
 #
+# daemontools source install function
+#
+
+function require() {
+	if ! which $1 >/dev/null 2>&1;
+	then
+		echo "This install needs $1 to succeed."
+		if test -n "${INSTALLHINT}";
+		then
+			echo "You can try: ${INSTALLHINT} $1"
+		fi
+		exit;
+	fi;
+}
+
+function dtsrcinstall() {
+	require wget
+	require patch
+	mkdir /package
+	chmod 1755 /package
+	cd /package
+	wget http://cr.yp.to/daemontools/daemontools-0.76.tar.gz
+	tar xzvf daemontools-0.76.tar.gz
+	rm -f daemontools-0.76.tar.gz
+	cd admin/daemontools-0.76/src
+	wget http://www.qmailrocks.org/downloads/patches/daemontools-0.76.errno.patch
+	patch < daemontools-0.76.errno.patch
+	cd ..
+	package/install
+	return $?
+}
+
+#
 # Determine linux flavour
 #
 
-if [ -f /etc/gentoo-release ];
-then
-	FLAVOUR=gentoo
-	INSTALLDT="emerge daemontools"
-	if [ -z "${SERVICE}" ];
-	then
+case $distro in
+	Gentoo)
+		INSTALLHINT="emerge"
+		INSTALLDT="emerge daemontools"
+		INSTALLDTHELP="Oops... how did you make emerge fail??"
+		if [ -z "${SERVICE}" ];
+		then
+			SERVICE="/service"
+		fi
+		RCDT="rc-update add svscan default"
+		RCDTDETECT="rc-status default | grep svscan | grep started > /dev/null"
+		RCSTART="/etc/init.d/svscan start"
+		RCSTARTDETECT="ps -ef | grep /usr/bin/svscan | grep -v grep > /dev/null"
+		;;
+	Debian)
+		INSTALLHINT="apt-get install"
+		INSTALLDT="apt-get install daemontools-installer && build-daemontools"
+		INSTALLDTHELP="If the package is not found, please make sure you have the contrib tree in your /etc/apt/sources.list. 
+The line should read something like:
+
+   deb http://ftp.debian.org/debian/ stable main contrib
+   
+Don't forget to do 
+
+   apt-get update
+   
+after you change the line!
+"	
 		SERVICE="/service"
-	fi
-	RCDT="rc-update add svscan default"
-	RCSTART="/etc/init.d/svscan start"
-else if [ -f /etc/debian_version ];
-then
-	FLAVOUR=debian
-	INSTALLDT="apt-get install daemontools"
-	SERVICE="/service"
-	RCSTART="/command/svscanboot&"
-else if [ -f /etc/redhat_release ];
-then
-	FLAVOUR=redhat
-else
-	if [ ! -n "${force}" ];
-	then
+		RCDT=""
+		RCDTDETECT="true"
+		RCSTART="/command/svscanboot&"
+		RCSTARTDETECT="true"
+		;;
+	Fedora)
+		INSTALLHINT="yum install"
+		INSTALLDT="dtsrcinstall"
+		INSTALLDTHELP="Ehh?? how did you do that??"
+		SERVICE="/service"
+		RCDT=""
+		RCDETECT="true"
+		RCSTART=""
+		RCSTARTDETECT="true"
+		;;
+	SUSE)
+		INSTALLHINT="yast -i"
+		INSTALLDT="dtsrcinstall"
+		INSTALLDTHELP="Ehh?? how did you do that??"
+		SERVICE="/service"
+		RCDT=""
+		RCDETECT="true"
+		RCSTART=""
+		RCSTARTDETECT="true"
+		;;
+	*)
 		echo "Unsupported linux flavour, please report:"
 		echo "  * name of distribution"
 		echo "  * the name of the release file (most likely /etc/<distribution>-release)"
 		echo "  * command to install daemontools package"
 		echo "  * the default service directory of the daemontools package"
 		echo "  * the command to add daemontools to the boot up sequence"
+		echo "  * detected as ${distro}"
 		echo " Use --force to force daemontools installation from source."
 		echo "Thank you."
 		exit;
-	else
-		echo "Forcing installation of daemontools from source."
-	fi;
-fi
-fi
-fi
+		;;
+esac
 
 if [ -d ${SERVICE} ];
 then
 	echo Daemontools Installed.
 else
-	if [ "${FLAVOUR}" = "gentoo" ];
+	if ! eval ${ECHO} ${INSTALLDT};
 	then
-		${ECHO} ${INSTALLDT}
-	else 
-		if [ "${force}" != "1" ];
-		then
-			if [ "${FLAVOUR}" = "debian" ];
-			then
-				echo "You can download and install the daemontools packages from"
-				echo "    http://smarden.sunsite.dk/pape/Debian/daemontools.html"
-				echo "or use --force to install from source (not recommended)."
-				exit;
-			fi
-		fi
-
-		echo Installing daemontools from source.
-		mkdir /package
-		chmod 1755 /package
-		cd /package
-		wget http://cr.yp.to/daemontools/daemontools-0.76.tar.gz
-		tar zxvf daemontools-0.76.tar.gz
-		rm -f daemontools-0.76.tar.gz
-		cd admin/daemontools-0.76/src
-		wget http://www.qmailrocks.org/downloads/patches/daemontools-0.76.errno.patch
-		patch < daemontools-0.76.errno.patch
-		cd ..
-		package/install
-		SERVICE=/service
-	fi;
+		echo "Install failed."
+		echo
+		echo "${INSTALLDTHELP}"
+		exit;
+	fi
 fi
 
-echo "Creating user..."
-${ECHO} groupadd ${GROUP}
-${ECHO} useradd -g ${GROUP} -s ${USERSHELL} ${USER}
+if ! grep ${GROUP} /etc/group >/dev/null;
+then
+	echo "Creating group ${GROUP}..."
+	${ECHO} groupadd ${GROUP}
+fi
+if ! grep ${USER} /etc/passwd > /dev/null;
+then
+	echo "Creating user ${USER} with shell ${USERSHELL}..."
+	${ECHO} useradd -g ${GROUP} -s ${USERSHELL} ${USER}
+fi
 
-echo "Creating directories..."
-${ECHO} mkdir -p --verbose ${HOME}/
-${ECHO} mkdir -p --verbose ${HOME}/supervise
-${ECHO} mkdir -p --verbose ${HOME}/log
-${ECHO} mkdir -p --verbose ${HOME}/log/supervise
-${ECHO} mkdir -p --verbose ${HOME}/log/main
-
-${ECHO} chown -R root:root ${HOME}/
-${ECHO} chown aquila:aquila ${HOME}/log/main
+if ! test -d ${HOME}/service;
+then
+	echo "Creating directories..."
+	${ECHO} mkdir -p --verbose ${HOME}/service
+	${ECHO} mkdir -p --verbose ${HOME}/service/supervise
+	${ECHO} mkdir -p --verbose ${HOME}/service/log
+	${ECHO} mkdir -p --verbose ${HOME}/service/log/supervise
+	${ECHO} mkdir -p --verbose ${HOME}/service/log/main
+	${ECHO} chown -R root:root ${HOME}/service
+	${ECHO} chown aquila:aquila ${HOME}/service/log/main
+fi;
 
 echo "Creating config files..."
 for i in ${CONFIGFILES};
 do
-	${ECHO} touch ${HOME}/$i
-	${ECHO} chown aquila:aquila ${HOME}/$i
+	${ECHO} touch ${HOME}/service/$i
+	${ECHO} chmod a-rwx,u+rw ${HOME}/service/$i
+	${ECHO} chown aquila:aquila ${HOME}/service/$i
 done;
 
 echo "Creating run files..."
@@ -228,48 +293,70 @@ echo "Creating run files..."
 if [ ! -n "${ECHO}" ];
 then
 
-cat > ${HOME}/run <<EOF
+cat > ${HOME}/service/run <<EOF
 #!/bin/sh
 
-ulimit -n 4096
+ulimit -n 20480
 ulimit -c 20971510
 exec setuidgid ${USER} ${PREFIX}/bin/aquila 2>&1
 EOF
 
-cat > ${HOME}/log/run <<EOF
+cat > ${HOME}/service/log/run <<EOF
 #!/bin/sh
 exec setuidgid ${USER} multilog t s9999999 ./main
 EOF
 
 else
-	echo " creating" ${HOME}/run
-	echo " creating" ${HOME}/log/run
+	echo " creating" ${HOME}/service/run
+	echo " creating" ${HOME}/service/log/run
 fi;
 
 #making run files executable.
-${ECHO} chmod a+x ${HOME}/run
-${ECHO} chmod a+x ${HOME}/log/run
+${ECHO} chmod a-w,a+rx ${HOME}/service/run
+${ECHO} chmod a-w,a+rx ${HOME}/service/log/run
 
 #warning user.
 echo
-cat <<EOF
-Aquila Daemontools service directory installed in ${HOME}
-Do not forget:
- * to add a link from the main service directory to the aquila service 
+
+echo "Aquila Daemontools service directory installed in ${HOME}"
+echo
+
+WARNING=""
+
+if ! test -d ${SERVICE}/aquila
+then
+WARNING="${WARNING}
+Do not forget: 
+ - to add a link from the main service directory to the aquila service
    directory:
-        ln -s ${HOME} ${SERVICE}/aquila
-EOF
+        ln -s ${HOME}/service ${SERVICE}/aquila
+"
+fi
+
 if test "${RCDT}" != ""
 then
-cat <<EOF
- * Add daemontools to standard system boot up:
+if ! eval ${RCDTDETECT}
+then
+WARNING="${WARNING}
+ - Add daemontools to standard system boot up:
         ${RCDT}
-EOF
+"
 fi
-cat <<EOF
+fi
 
-If you have done the above two things, Aquila will be automatically started at 
-system boot and restarted should it crash.
+if ! test -z "${WARNING}"
+then
+	echo "${WARNING}"
+	echo -n "If you have done the above, "
+fi
+
+echo "Aquila will be started at system boot and restarted should it stop."
+echo
+
+if ! eval ${RCSTARTDETECT}
+then
+cat <<EOF
 To start the service now, do:
         ${RCSTART}
 EOF
+fi
